import type { LucideIcon } from 'lucide-react';
import {
  SquareTerminal,
  FolderGit2,
  Settings,
  LayoutDashboard,
  Bot,
  Cpu,
  GitMerge,
  Server,
  Code2,
  Terminal,
  Zap,
  Ghost,
  Clock,
  Loader2,
  PauseCircle,
  MessageSquareDashed,
  Eye,
  CheckCircle2,
  XCircle,
  Pause,
  Play,
  Plus,
  FileJson,
  Trash2,
  Activity,
  MoreVertical,
  SlidersHorizontal,
  Link,
  Send,
  ShieldAlert,
  HelpCircle,
  GitPullRequest,
  Check,
  Lock,
  Edit2,
  AlertOctagon,
  CheckCircle,
  Info,
  AlertCircle,
  AlertTriangle,
  X,
  LogIn,
  LogOut,
  Folder,
  FolderOpen,
  FolderPlus,
  RefreshCw,
  HardDrive,
  ChevronRight,
  ChevronsUp,
  KeyRound,
  Database,
  Copy,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  'terminal-square': SquareTerminal,
  'folder-git-2': FolderGit2,
  settings: Settings,
  'layout-dashboard': LayoutDashboard,
  bot: Bot,
  cpu: Cpu,
  'git-merge': GitMerge,
  server: Server,
  'code-2': Code2,
  terminal: Terminal,
  zap: Zap,
  ghost: Ghost,
  clock: Clock,
  'loader-2': Loader2,
  'pause-circle': PauseCircle,
  'message-square-dashed': MessageSquareDashed,
  eye: Eye,
  'check-circle-2': CheckCircle2,
  'x-circle': XCircle,
  pause: Pause,
  play: Play,
  plus: Plus,
  'file-json': FileJson,
  'trash-2': Trash2,
  activity: Activity,
  'more-vertical': MoreVertical,
  'sliders-horizontal': SlidersHorizontal,
  link: Link,
  send: Send,
  'shield-alert': ShieldAlert,
  'help-circle': HelpCircle,
  'git-pull-request': GitPullRequest,
  check: Check,
  lock: Lock,
  'edit-2': Edit2,
  'alert-octagon': AlertOctagon,
  'check-circle': CheckCircle,
  info: Info,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  x: X,
  'log-in': LogIn,
  'log-out': LogOut,
  folder: Folder,
  'folder-open': FolderOpen,
  'folder-plus': FolderPlus,
  'refresh-cw': RefreshCw,
  'hard-drive': HardDrive,
  'chevron-right': ChevronRight,
  'chevrons-up': ChevronsUp,
  'key-round': KeyRound,
  database: Database,
  copy: Copy,
};

export function Icon({
  name,
  className = '',
  size = 24,
}: {
  name: string;
  className?: string;
  size?: number;
}) {
  const Cmp = ICONS[name] ?? SquareTerminal;
  return <Cmp className={className} size={size} aria-hidden="true" />;
}